/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit collection
         * @description Update the core details of a collection such as the name, summary, description, and category.
         */
        patch: operations["editCollection"];
        trace?: never;
    };
    "/games/{game_domain}/trending-mods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trending mods for a game
         * @description Public feed of the top 5 trending mods for a game over the past
         *     `game.hot_mods_days` days, ranked by total endorsements.
         *     Excludes adult and unpublished mods.
         */
        get: operations["getTrendingMods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mods/{game_scoped_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod
         * @description Retrieve specified mod, from a specified game.
         */
        get: operations["getMod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mod-files/{game_scoped_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file
         * @description Retrieve a specific file for a game.
         */
        get: operations["getModFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mods/{id}/file-update-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file update groups
         * @description Retrieve all file update groups for a given mod.
         */
        get: operations["getModFileUpdateGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mods/{id}/toggle-legacy-mod-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle legacy mod requirements for a mod
         * @description Sets whether the given mod should use the legacy mod-level requirements.
         *     When `enabled` is `true`, the mod uses legacy mod-level requirements; when
         *     `false`, it uses file-to-file requirements.
         */
        put: operations["toggleLegacyModRequirements"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a file update group
         * @description Updates the name of an existing file update group by its ID.
         */
        put: operations["updateModFileUpdateGroup"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-files/{id}/dependencies/ranges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file dependency ranges
         * @description Retrieve dependency ranges for a given mod file. Each dependency definition
         *     contains a set of version ranges within update groups that satisfy the dependency.
         */
        get: operations["getModFileDependencyRanges"];
        /**
         * Update mod file dependency ranges
         * @description Replace all dependency range definitions for a given mod file. Each
         *     dependency definition contains an array of version ranges. Ranges
         *     within the same definition represent alternatives (OR). Separate
         *     definitions are independent requirements (AND).
         *
         *     A range is defined by a min_version_id (required) and an optional
         *     max_version_id. Both must refer to versions within the same file
         *     update group. When max_version_id is null the range is open-ended
         *     (no upper bound).
         */
        put: operations["setModFileDependencyRanges"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-files/{id}/dependencies/materialized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file materialized dependencies
         * @description Retrieve materialized dependencies for a given mod file. Resolves the
         *     stored dependency ranges into concrete candidate files grouped by update
         *     group.
         */
        get: operations["getModFileDependencyMaterialized"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file-update-groups/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file update group versions
         * @description Retrieve all versions for a given file update group.
         */
        get: operations["getFileUpdateGroupVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-group-versions/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move multiple file update group versions
         * @description Moves one or more file update group versions to a new position relative to
         *     another version, which may be in a different group.
         *
         *     Versions are inserted in the order given by `version_ids`.
         *     `version_ids` is expected to be ordered from earliest to latest version.
         *
         *     **Example:** Given an update group with versions `[v1.0.0, v1.1.0, v2.0.0]`
         *     (earliest to latest), moving `[v1.0.1, v1.0.2]` with `relative_placement: "after"`
         *     targeting `v1.0.0` produces `[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v2.0.0]`.
         */
        post: operations["moveFileUpdateGroupVersions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-group-versions/move-to-new-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move multiple file update group versions into a new file update group
         * @description Moves one or more file update group versions into a new file update group with the specified name.
         *
         *     Versions are inserted in the order given by `version_ids`.
         *     `version_ids` is expected to be ordered from earliest to latest version.
         */
        post: operations["moveFileUpdateGroupVersionsToNewGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upload
         * @description Get the state of an upload session.
         *     ### Next steps
         *     * Once the `state` is `available`, the upload may be used to [create a mod file](#tag/mod-files/operation/createModFile).
         *     ### FAQ
         *     * How do I create an upload?
         *        * Use [create upload](#tag/uploads/operation/createUpload) to start a new upload session.
         */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create upload
         * @description Creates a new upload session. This allows you to upload data for a new mod file.
         *
         *     ⚠️ Files larger than 100 MiB must use a [multi part upload](#tag/uploads/operation/createMultipartUpload).
         *
         *     ### Next steps
         *     * Call `PUT` with your file data to the returned `presigned_url`. Recommended for files up to 100 MiB.
         *     * Once all data is uploaded, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/multipart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create multipart upload
         * @description Creates a new multipart upload session. This allows you to upload data for a new mod file.
         *
         *     💡 Files smaller than 100 MiB can use the simpler [single part upload](#tag/uploads/operation/createUpload).
         *
         *     ### Next steps
         *     Multipart upload uses the [Amazon S3 multipart upload specification](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).
         *
         *     * Call `PUT` with your file data to each `part_presigned_urls`.
         *        * Each part must be `part_size_bytes` bytes, apart from the final part which may be smaller.
         *        * Retrieve the `ETag` response header value from each part upload.
         *     * Once all parts are uploaded, call `POST` to the `complete presigned_url` with [XML post data](#multipart-resources) describing
         *       the `ETag` for each part.
         *     * Once multipart complete is called, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         *
         *     ### Multipart resources
         *
         *     Sample XML for completing the multipart upload:
         *
         *     ```xml
         *     <CompleteMultipartUpload>
         *       <Part>
         *         <PartNumber>1</PartNumber>
         *         <ETag>a54357aff0632cce46d942af68356b38</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>2</PartNumber>
         *         <ETag>0c78aef83f66abc1fa1e8477f296d394</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>3</PartNumber>
         *         <ETag>acbd18db4cc2f85cedef654fccc4a4d8</ETag>
         *       </Part>
         *     </CompleteMultipartUpload>
         *     ```
         */
        post: operations["createMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise upload
         * @description Closes the upload session once all data is uploaded. Sessions must be closed before you can use the upload as a mod file.
         *     ### Next steps
         *     * Wait for the upload to be ready for use as a mod file. Use [get upload](#tag/uploads/operation/getUpload) to check that `state`
         *       is `available`.
         *     * [Create a mod file](#tag/mod-files/operation/createModFile) from this upload.
         */
        post: operations["finaliseUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a collection
         * @description Creates a collection and claims an upload using the upload_id from a finalised [upload session](#tag/uploads/operation/createUpload).
         */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a collection revision
         * @description Creates a collection revision claims an upload using the upload_id from a finalised [upload session](#tag/uploads/operation/createUpload).
         */
        post: operations["createCollectionRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create mod file
         * @description Creates a new mod file using the data from a finalised [upload session](#tag/uploads/operation/createUpload).
         *
         *     Note that this is for entirely new files, not new versions of existing files.
         */
        post: operations["createModFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-groups/{group_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new update group version (updates a mod file)
         * @description Creates a new version of an update group (tied to a mod file), the upload specified in the request becomes the most recent entry in the update chain.
         */
        post: operations["createUpdateGroupVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An RFC 9457 Problem Details object. */
        ProblemDetails: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type.
             */
            type: string;
            /** @description A short, human-readable summary of the problem type. */
            title: string;
            /**
             * @description The HTTP status code.
             * @example 404
             */
            status: number;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail: string;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance: string;
        };
        /** @description RFC 9457 Problem Details extended with validation errors. */
        ValidationProblem: components["schemas"]["ProblemDetails"] & {
            /** @description List of validation errors. */
            errors: components["schemas"]["ValidationProblemItem"][];
        };
        /** @description A single validation error with a JSON pointer to the problematic field. */
        ValidationProblemItem: {
            /** @description Human-readable description of the validation error. */
            detail: string;
            /**
             * @description A JSON Pointer (RFC 6901) to the field that caused the error.
             * @example /collection_data/collection_manifest/mods/0/source/mod_id
             */
            pointer: string;
        };
        EditCollectionRequest: {
            /** @description Name of the collection. */
            name?: string;
            /** @description Collection summary. */
            summary?: string;
            /** @description Description of the collection. */
            description?: string;
            /** @description ID of the parent category. */
            category_id?: number | null;
        };
        TrendingModsResponse: {
            mods: components["schemas"]["TrendingMod"][];
        };
        /** @description A trending mod entry in the public marketing feed. */
        TrendingMod: {
            /** @description The mod name. */
            name: string;
            /** @description The display name of the user who uploaded the mod. */
            author?: string | null;
            /** @description Short summary shown on the mod listing. */
            summary?: string | null;
            /** @description URL of the mod's main image. */
            picture_url?: string | null;
            /** @description Canonical URL of the mod page on nexusmods.com. */
            mod_page_url: string;
        };
        GetModDetails: components["schemas"]["Mod"];
        Mod: {
            /** @description The unique identifier for the mod. */
            id: string;
            /** @description The game-scoped identifier for the mod. */
            game_scoped_id: string;
            /** @description The unique identifier for game this mod belongs to. */
            game_id: string;
            /** @description Mod name (only shown if mod is available). */
            name?: string | null;
        };
        GetModFileDetails: components["schemas"]["ModFile"];
        ModFile: {
            /** @description The unique identifier for the mod file. */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description The unique identifier for the game this mod file belongs to. */
            game_id: string;
            /** @description The game-scoped identifier for the mod this mod file belongs to. */
            mod_game_scoped_id: string;
            update_group_version: components["schemas"]["ModFileUpdateGroupVersion"];
        };
        /** @description A file update group. */
        ModFileUpdateGroup: {
            /** @description The unique identifier for the file update group. */
            readonly id: string;
            /** @description The name of the file update group. */
            name: string;
        };
        /** @description A file update group enriched with aggregate stats across its versions. */
        ModFileUpdateGroupWithAggregates: components["schemas"]["ModFileUpdateGroup"] & {
            /** @description True if the group contains at least one version/file with an active category (main, update, optional, or miscellaneous). */
            is_active: boolean;
            /**
             * Format: date-time
             * @description The most recent file upload date across all versions in the group. Null if the group has no files.
             */
            last_file_uploaded_at: string | null;
            /** @description The total number of versions (files) in the group. */
            versions_count: number;
            /** @description The number of archived versions (files) in the group. */
            archived_count: number;
            /** @description The number of removed versions (files) in the group. */
            removed_count: number;
        };
        /** @description A file update group with its associated mod. */
        ModFileUpdateGroupWithMod: components["schemas"]["ModFileUpdateGroup"] & {
            mod: components["schemas"]["MinimalMod"];
        };
        ModFileUpdateGroupVersion: {
            /**
             * Format: decimal
             * @description Position within the file update group.
             */
            position: string;
            /** @description File update group ID. */
            group_id: string;
        };
        /** @description A minimal representation of a mod file. */
        MinimalModFile: {
            /** @description The unique identifier for the mod file. */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description The name of the mod file. */
            name: string;
            /** @description The version of the mod file. */
            version: string;
            category: components["schemas"]["ModFileCategory"];
            /**
             * Format: date-time
             * @description The date and time the file was uploaded.
             */
            uploaded_at: string;
            /** @description Whether this file is the primary file for the mod. The primary file represents the default download file for a mod page. There can be at most one primary file per mod. Defaults to false if omitted. */
            is_primary?: boolean;
        };
        /** @enum {string} */
        ModFileCategory: "main" | "update" | "optional" | "old_version" | "miscellaneous" | "removed" | "archived" | "unknown";
        ModFileUpdateGroupsResponse: {
            groups: components["schemas"]["ModFileUpdateGroupWithAggregates"][];
        };
        ModFileUpdateGroupVersionsResponse: {
            versions: components["schemas"]["ModFileUpdateGroupVersionWithFile"][];
        };
        ModFileUpdateGroupVersionWithFile: {
            /** @description The unique identifier for the file update group version. */
            id: string;
            /**
             * Format: decimal
             * @description Position within the file update group.
             */
            position: string;
            file: components["schemas"]["MinimalModFile"];
        };
        /** @description A file update group version with its file and parent group. */
        ModFileUpdateGroupVersionWithFileAndGroup: components["schemas"]["ModFileUpdateGroupVersionWithFile"] & {
            group: components["schemas"]["ModFileUpdateGroup"];
        };
        /** @description A file update group with its associated mod and versions. */
        DependencyCandidateUpdateGroup: {
            /** @description The unique identifier for the file update group. */
            id: string;
            /** @description The name of the file update group. */
            name: string;
            mod: components["schemas"]["MinimalMod"];
            candidate_versions: components["schemas"]["ModFileUpdateGroupVersionWithFile"][];
        };
        /** @description A minimal representation of a mod. */
        MinimalMod: {
            /** @description The unique identifier for the mod. */
            id: string;
            /** @description The game-scoped identifier for the mod. */
            game_scoped_id: string;
            /** @description The name of the mod. */
            name: string;
            game: components["schemas"]["MinimalGame"];
            /** @description The URL of the mod's thumbnail image. */
            thumbnail_url?: string | null;
            status?: components["schemas"]["ModStatus"];
            /** @description Whether the mod is marked as adult content. */
            adult_content?: boolean | null;
        };
        /**
         * @description The effective visibility status of a mod.
         * @enum {string}
         */
        ModStatus: "published" | "not_published" | "hidden" | "under_moderation" | "removed" | "removed_by_staff";
        /** @description A minimal representation of a game. */
        MinimalGame: {
            /** @description The unique identifier for the game. */
            id: string;
            /** @description The name of the game. */
            name: string;
            /**
             * @description The URL-friendly slug for the game.
             * @example skyrimspecialedition
             */
            domain_name: string;
        };
        UpdateModFileDependencyRangesRequest: {
            dependency_definitions: components["schemas"]["ModFileDependencyRangeDefinitionInput"][];
        };
        ModFileDependencyRangeDefinitionInput: {
            ranges: components["schemas"]["ModFileDependencyRangeInput"][];
        };
        ModFileDependencyRangeInput: {
            /** @description The ID of the file update group version representing the lower bound of the range. */
            min_version_id: string;
            /** @description The ID of the file update group version representing the upper bound of the range. Null means open-ended (no upper bound). */
            max_version_id?: string | null;
        };
        ToggleLegacyModRequirementsRequest: {
            /** @description Whether legacy mod-level requirements should be used for this mod. */
            enabled: boolean;
        };
        UpdateModFileUpdateGroupRequest: {
            /** @description The name of the file update group. */
            name: string;
        };
        MoveFileUpdateGroupVersionsRequest: {
            /**
             * @description The unique identifiers for the file update group versions to move.
             *     Versions are inserted in this order, and `version_ids` is expected to be ordered from earliest to latest version.
             */
            version_ids: string[];
            target: components["schemas"]["MoveToPosition"];
        };
        /** @description Place the moved versions earlier (`before`) or later (`after`) with respect to the target version. */
        MoveToPosition: {
            /** @description The unique identifier of the version to position relative to. */
            target_version_id: string;
            relative_placement: components["schemas"]["RelativePlacement"];
        };
        /**
         * @description `before`: earlier than the target. `after`: later than the target.
         * @enum {string}
         */
        RelativePlacement: "before" | "after";
        /** @description The result of a bulk move operation. */
        MoveFileUpdateGroupVersionsResponse: {
            /** @description The updated versions reflecting their new group and order. */
            versions: components["schemas"]["ModFileUpdateGroupVersionWithFile"][];
            /**
             * @description A list of source groups that had versions removed but still contain
             *     other versions.
             */
            modified_source_groups?: components["schemas"]["ModFileUpdateGroupWithAggregates"][];
            /**
             * @description A list of IDs for any source groups that were automatically deleted
             *     because they became empty as a result of this move.
             */
            deleted_source_group_ids?: string[];
            target_group: components["schemas"]["ModFileUpdateGroupWithAggregates"];
        };
        MoveFileUpdateGroupVersionsToNewGroupRequest: {
            /**
             * @description The unique identifiers for the file update group versions to move.
             *     Versions are inserted in this order, and `version_ids` is expected to be ordered from earliest to latest version.
             */
            version_ids: string[];
            /** @description The name of the new file update group. */
            group_name: string;
        };
        /** @description The result of a bulk move operation. */
        MoveFileUpdateGroupVersionsToNewGroupResponse: {
            /** @description The updated versions reflecting their new group and order. */
            versions: components["schemas"]["ModFileUpdateGroupVersionWithFile"][];
            /**
             * @description A list of source groups that had versions removed but still contain
             *     other versions.
             */
            modified_source_groups?: components["schemas"]["ModFileUpdateGroupWithAggregates"][];
            /**
             * @description A list of IDs for any source groups that were automatically deleted
             *     because they became empty as a result of this move.
             */
            deleted_source_group_ids?: string[];
            new_group: components["schemas"]["ModFileUpdateGroupWithAggregates"];
        };
        ModFileDependencyRangesResponse: {
            dependency_definitions: components["schemas"]["ModFileDependencyDefinitionWithRanges"][];
        };
        ModFileDependencyDefinitionWithRanges: {
            /** @description The unique identifier for the dependency definition. */
            id: string;
            ranges: components["schemas"]["ModFileDependencyRange"][];
        };
        ModFileDependencyRange: {
            /** @description The unique identifier for the dependency range. */
            id: string;
            target_group: components["schemas"]["ModFileUpdateGroupWithMod"];
            min_version: components["schemas"]["ModFileUpdateGroupVersionWithFileAndGroup"];
            max_version: components["schemas"]["ModFileUpdateGroupVersionWithFileAndGroup"] | null;
        };
        ModFileDependencyMaterializedResponse: {
            dependencies: components["schemas"]["MaterializedDependency"][];
        };
        /** @description A materialized dependency definition with its resolved candidate groups and versions. */
        MaterializedDependency: {
            /** @description The unique identifier for the dependency definition. */
            id: string;
            candidate_groups: components["schemas"]["DependencyCandidateUpdateGroup"][];
        };
        CreateModFileRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            upload_id: string;
            /**
             * @description The unique identifier for the mod this file belongs to.
             *
             *     * Use [get mod](#tag/mods/operation/getMod) to get the game scoped ID for a mod using the data from a site URL e.g.
             *       `/skyrimspecialedition/mods/12604`.
             */
            mod_id: string;
            /** @description Mod file name. */
            name: string;
            /** @description Mod file version. */
            version: string;
            /** @description Description of the mod file. */
            description?: string | null;
            file_category: components["schemas"]["NewModFileCategory"];
            /**
             * @description Whether this file is the default download for mod managers.
             * @default false
             */
            primary_mod_manager_download: boolean;
            /**
             * @description Whether mod manager downloads are enabled for this file.
             * @default true
             */
            allow_mod_manager_download: boolean;
            /**
             * @description Whether to show a requirements popup when downloading this file.
             * @default false
             */
            show_requirements_pop_up: boolean;
        };
        CreateUploadRequest: {
            /**
             * Format: int64
             * @description Size of file in bytes.
             */
            size_bytes: number;
            /** @description User-defined filename. */
            filename: string;
        };
        CreateUploadSuccess: {
            /** @description Presigned URL. */
            presigned_url: string;
        } & components["schemas"]["Upload"];
        CreateMultipartUploadSuccess: {
            /**
             * Format: int64
             * @description Size of each part in bytes.
             */
            part_size_bytes: number;
            /** @description Presigned URLs for each upload part. */
            part_presigned_urls: string[];
            /** @description Presigned URL to complete upload. */
            complete_presigned_url: string;
        } & components["schemas"]["Upload"];
        FinaliseUploadSuccess: components["schemas"]["Upload"];
        GetUploadSuccess: components["schemas"]["Upload"];
        CreateModFileSuccess: components["schemas"]["UploadModFile"];
        Upload: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            id: string;
            user: components["schemas"]["UploadUser"];
            state: components["schemas"]["UploadState"];
        };
        UploadUser: {
            /** @description The unique identifier for the user who owns this upload. */
            id: string;
        };
        UploadModFile: {
            /** @description The unique identifier for the mod file. */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description Mod file name. */
            name: string;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        /** @enum {string} */
        UploadState: "created" | "available";
        /** @enum {string} */
        NewModFileCategory: "main" | "optional" | "miscellaneous";
        CreateUpdateGroupVersionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            upload_id: string;
            /** @description Mod file name */
            name: string;
            /** @description Description of the mod file */
            description?: string | null;
            /** @description Mod file version */
            version: string;
            file_category: components["schemas"]["NewModFileCategory"];
            /** @description Whether this file is the default download for mod managers. */
            primary_mod_manager_download?: boolean;
            /** @description Whether mod manager downloads are enabled for this file. */
            allow_mod_manager_download?: boolean;
            /** @description Whether to show a requirements popup when downloading this file. */
            show_requirements_pop_up?: boolean;
            /**
             * @description Whether to archive the existing file when uploading a new version.
             * @default false
             */
            archive_existing_file: boolean;
            /** @description The unique identifier for the mod file version this version is replacing. */
            previous_version_id?: string | null;
        };
        CreateUpdateGroupVersionSuccess: components["schemas"]["UploadModFile"];
        CreateCollectionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload to claim against this new collection.
             */
            upload_id: string;
            collection_data: components["schemas"]["CollectionPayload"];
        };
        CreateCollectionSuccess: {
            /** @description The unique identifier for the collection. */
            id: string;
            /** @description The slug for the collection. */
            slug: string;
            /** @description The unique identifier for the initial collection revision. */
            revision_id: string;
            /** @description The revision number. */
            revision_number: number;
            revision_status: components["schemas"]["RevisionStatus"];
        };
        CreateCollectionRevisionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload to claim against this new collection.
             */
            upload_id: string;
            collection_data: components["schemas"]["CollectionPayload"];
        };
        CreateCollectionRevisionSuccess: {
            /** @description The unique identifier for the revision. */
            id: string;
            /** @description The unique identifier for the collection this revision belongs to. */
            collection_id: string;
            /** @description The revision number. */
            revision_number: number;
            revision_status: components["schemas"]["RevisionStatus"];
        };
        /** @description The data payload used to create a collection revision. */
        CollectionPayload: {
            /** @description Whether the collection includes adult content. */
            adult_content: boolean;
            collection_manifest: components["schemas"]["CollectionManifest"];
            /** @description Collection schema id. */
            collection_schema_id: number;
        };
        /** @description The JSON manifest that defines a collection. */
        CollectionManifest: {
            info: components["schemas"]["CollectionManifestInfo"];
            /** @description List of mod resources for the manifest. */
            mods: components["schemas"]["CollectionManifestMod"][];
        };
        /** @description The info section of the JSON manifest. */
        CollectionManifestInfo: {
            /** @description The collection author's name. */
            author: string;
            /** @description The url of the author's profile. */
            author_url?: string | null;
            /** @description The name of the collection. */
            name: string;
            /** @description A description of the collection. */
            description?: string | null;
            /** @description A short summary of the collection. */
            summary?: string | null;
            /** @description The domain name of the game. */
            domain_name: string;
            /** @description A list of game versions that this revision has been tested with. */
            game_versions?: string[] | null;
        };
        /** @description Defines a mod to be used in a collection as part of the manifest. */
        CollectionManifestMod: {
            /** @description The name of the mod. */
            name: string;
            /** @description The mod version. */
            version: string;
            /** @description Whether the mod is required for this collection. */
            optional: boolean;
            /** @description The domain name of the game for the mod. */
            domain_name: string;
            source: components["schemas"]["CollectionManifestModSource"];
            /** @description The name of the mod author. */
            author?: string | null;
        };
        /** @description Source information for a mod (nexus or other) as part of the manifest. */
        CollectionManifestModSource: {
            type: components["schemas"]["ModSource"];
            /** @description The identifier of the mod source for this collection manifest. */
            mod_id?: string;
            /** @description The identifier of the file associated with the mod in this collection manifest. */
            file_id?: string;
            /** @description An MD5 hash of the file for verification. */
            md5?: string | null;
            /** @description The file size in kb. */
            file_size?: number | null;
            update_policy?: components["schemas"]["UpdatePolicy"];
            /** @description Logical file name of the mod resource. */
            logical_filename?: string | null;
            /** @description File expression of the mod resource. */
            file_expression?: string | null;
            /** @description The direct url of the file. */
            url?: string | null;
            /** @description Does the mod include adult content. */
            adult_content?: boolean | null;
        };
        /**
         * @description Used to define the source of a mod. Useful for informing Collections how to retrieve mods.
         * @enum {string}
         */
        ModSource: "nexus" | "direct" | "browse" | "manual" | "bundle";
        /**
         * @description The status of a collection revision.
         * @enum {string}
         */
        RevisionStatus: "draft" | "published" | "retracted";
        /**
         * @description Available update policies of a file resource
         * @enum {string}
         */
        UpdatePolicy: "exact" | "latest" | "prefer";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    editCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the collection. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditCollectionRequest"];
            };
        };
        responses: {
            /** @description Successfully updated the collection. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The collection was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTrendingMods: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game domain name (e.g. `skyrimspecialedition`). */
                game_domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top trending mods. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TrendingModsResponse"];
                    };
                };
            };
            /** @description Game not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getMod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /**
                 * @description The game-scoped identifier for the mod.
                 *
                 *     This is the mod identifier which appears in URLs on the site e.g. `12604` from path `/skyrimspecialedition/mods/12604`.
                 */
                game_scoped_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetModDetails"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /** @description The game-scoped identifier for the mod file. */
                game_scoped_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod file details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetModFileDetails"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFileUpdateGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mod's file update groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ModFileUpdateGroupsResponse"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Access to the mod is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    toggleLegacyModRequirements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleLegacyModRequirementsRequest"];
            };
        };
        responses: {
            /** @description Successfully updated the mod's legacy mod requirements enabled state. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateModFileUpdateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the file update group to update. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The new data for the file update group. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModFileUpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Successfully updated the file update group. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file update group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFileDependencyRanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod file. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mod file's dependency ranges. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModFileDependencyRangesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setModFileDependencyRanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod file (i.e. the file to create dependency ranges for). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModFileDependencyRangesRequest"];
            };
        };
        responses: {
            /** @description Successfully updated the mod file dependency ranges. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFileDependencyMaterialized: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod file. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mod file's materialized dependencies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModFileDependencyMaterializedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getFileUpdateGroupVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the file update group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file update group's versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ModFileUpdateGroupVersionsResponse"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The file update group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    moveFileUpdateGroupVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFileUpdateGroupVersionsRequest"];
            };
        };
        responses: {
            /** @description The versions were moved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveFileUpdateGroupVersionsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The file update group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    moveFileUpdateGroupVersionsToNewGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFileUpdateGroupVersionsToNewGroupRequest"];
            };
        };
        responses: {
            /** @description The new group was created, and the versions were moved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveFileUpdateGroupVersionsToNewGroupResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The file update group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload ID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload ID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateMultipartUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    finaliseUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FinaliseUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRequest"];
            };
        };
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateCollectionSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"] | components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    createCollectionRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the collection this revision will belong to. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRevisionRequest"];
            };
        };
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateCollectionRevisionSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"] | components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    createModFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModFileRequest"];
            };
        };
        responses: {
            /** @description ModFile */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateModFileSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createUpdateGroupVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the update group. */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpdateGroupVersionRequest"];
            };
        };
        responses: {
            /** @description UpdateGroupVersion */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateUpdateGroupVersionSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
