export type DifficultyPreset = Partial<
  Record<string, string | number | boolean>
>;

export const DIFFICULTY_PRESETS: Record<string, DifficultyPreset> = {
  Casual: {
    ExpRate: 3.0,
    PalCaptureRate: 2.0,
    PalSpawnNumRate: 1.0,
    PalDamageRateAttack: 0.5,
    PalDamageRateDefense: 0.3,
    PlayerDamageRateAttack: 2.0,
    PlayerDamageRateDefense: 0.3,
    PlayerStomachDecreaceRate: 0.1,
    PlayerStaminaDecreaceRate: 0.1,
    PlayerAutoHPRegeneRate: 2.0,
    PlayerAutoHpRegeneRateInSleep: 3.0,
    PalStomachDecreaceRate: 0.1,
    PalStaminaDecreaceRate: 0.1,
    PalAutoHPRegeneRate: 2.0,
    PalAutoHpRegeneRateInSleep: 3.0,
    BuildObjectDamageRate: 0.5,
    BuildObjectDeteriorationDamageRate: 0.0,
    CollectionDropRate: 2.0,
    CollectionObjectHpRate: 0.5,
    CollectionObjectRespawnSpeedRate: 2.0,
    EnemyDropItemRate: 2.0,
    DeathPenalty: "None",
    bEnableInvaderEnemy: false,
    bEnableNonLoginPenalty: false,
    WorkSpeedRate: 2.0,
    PalEggDefaultHatchingTime: 10.0,
  },
  Normal: {
    ExpRate: 1.0,
    PalCaptureRate: 1.0,
    PalSpawnNumRate: 1.0,
    PalDamageRateAttack: 1.0,
    PalDamageRateDefense: 1.0,
    PlayerDamageRateAttack: 1.0,
    PlayerDamageRateDefense: 1.0,
    PlayerStomachDecreaceRate: 1.0,
    PlayerStaminaDecreaceRate: 1.0,
    PlayerAutoHPRegeneRate: 1.0,
    PlayerAutoHpRegeneRateInSleep: 1.0,
    PalStomachDecreaceRate: 1.0,
    PalStaminaDecreaceRate: 1.0,
    PalAutoHPRegeneRate: 1.0,
    PalAutoHpRegeneRateInSleep: 1.0,
    BuildObjectDamageRate: 1.0,
    BuildObjectDeteriorationDamageRate: 1.0,
    CollectionDropRate: 1.0,
    CollectionObjectHpRate: 1.0,
    CollectionObjectRespawnSpeedRate: 1.0,
    EnemyDropItemRate: 1.0,
    DeathPenalty: "Item",
    bEnableInvaderEnemy: true,
    bEnableNonLoginPenalty: true,
    WorkSpeedRate: 1.0,
    PalEggDefaultHatchingTime: 72.0,
  },
  Hard: {
    PalDamageRateAttack: 1.0,
    PalDamageRateDefense: 1.0,
    PlayerStomachDecreaceRate: 1.0,
    PlayerStaminaDecreaceRate: 1.0,
    PlayerAutoHPRegeneRate: 1.0,
    PlayerAutoHpRegeneRateInSleep: 1.0,
    PalStomachDecreaceRate: 1.0,
    PalStaminaDecreaceRate: 1.0,
    PalAutoHPRegeneRate: 1.0,
    PalAutoHpRegeneRateInSleep: 1.0,
    BuildObjectDamageRate: 1.0,
    BuildObjectDeteriorationDamageRate: 1.0,
    CollectionDropRate: 1.0,
    CollectionObjectHpRate: 1.0,
    CollectionObjectRespawnSpeedRate: 1.0,
    PalSpawnNumRate: 1.0,
    WorkSpeedRate: 1.0,
    bEnableInvaderEnemy: true,
    bEnableNonLoginPenalty: true,
    ExpRate: 0.8,
    PalCaptureRate: 0.8,
    PlayerDamageRateAttack: 0.5,
    PlayerDamageRateDefense: 4.0,
    EnemyDropItemRate: 0.5,
    PalEggDefaultHatchingTime: 72.0,
    DeathPenalty: "All",
  },
};
